/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlphongthigiaodienuser;

import CLassController.KetQua;
import CLassController.MonThi;
import CLassController.PhongThi;
import CLassController.SinhVien;

import CLassController.ThiSinh;
import LuuFile.Filee;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC
 */
public final class KetQuaUser extends javax.swing.JFrame {

    /**
     * Creates new form KetQuaUser
     */
    private final Filee db1 = new Filee();
    static String fileNamePT = "phongthi.txt";
    static String fileNameMT = "monthi.txt";
    static String fileNameTS = "thisinh.txt";
    static String fileNameKQ = "ketqua.txt";
    ArrayList<PhongThi> dsPT = new ArrayList<>();
    ArrayList<ThiSinh> dsTS = new ArrayList<>();
    ArrayList<MonThi> dsMT = new ArrayList<>();
    ArrayList<KetQua> dsKQ = new ArrayList<>();
    private final DefaultTableModel tblVeModel;
    public KetQuaUser() {
        initComponents();
        docFilePT(fileNamePT);
        docFileMT(fileNameMT);
        docFileTS(fileNameTS);  
        docFileKQ(fileNameKQ);
        fakeTV();
        
        tblVeModel = (DefaultTableModel) jTable1.getModel();
        showData(dsTS, tblVeModel);
    }
    
    ArrayList<SinhVien> dsTVCC = new ArrayList<>();
        public void fakeTV() {
        SinhVien a = new SinhVien("2020604551", "Nguyễn Văn A", 1990, "hà nội","HTTT05","CNTT");
        SinhVien b = new SinhVien("2020604552", "Nguyễn Văn B", 1990, "hà nội","HTTT05","CNTT");
        SinhVien c = new SinhVien("2020604553", "Nguyễn Văn C", 1990, "hà nội","HTTT05","CNTT");
        SinhVien d = new SinhVien("2020604554", "Nguyễn Văn D", 1990, "hà nội","HTTT05","CNTT");
        SinhVien e = new SinhVien("2020604555", "Nguyễn Văn E", 1990, "hà nội","HTTT05","CNTT");
        SinhVien f = new SinhVien("2020604556", "Nguyễn Văn F", 1990, "hà nội","HTTT05","CNTT");
        
         
       
        dsTVCC.add(a);
        dsTVCC.add(b);
        dsTVCC.add(c);
        dsTVCC.add(d);
        dsTVCC.add(e);
        dsTVCC.add(f);


    }
    public final <T> void showData(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if (t instanceof ThiSinh thiSinh) {
                
                
                String mamonthi = null, maketqua = "---",
                        diem = "chua co",monthi = null , tensv = null;                
                for(PhongThi pt : dsPT){
                    if(pt.getMaPhong().equals(thiSinh.getMaPhong())){
                        mamonthi = pt.getMaMonThi();
                    }
                }
                for(MonThi mt : dsMT){
                    if(mt.getMaMonThi().equals( mamonthi)){
                         monthi = mt.getTenMonThi();
                    }
                }
                for(SinhVien sv : dsTVCC){
                    if(sv.getMaSV().equals(thiSinh.getMaSV())){
                         tensv = sv.getTenSV();
                    }
                }

                for(KetQua kq : dsKQ){
                    if(kq.getsBD().equals(thiSinh.getsBD())){
                        maketqua = kq.getMaKetQua();
                        diem = Float.toString(kq.getDiem());
                    }
                }
                model.addRow(new Object[]{ maketqua, tensv, thiSinh.getsBD(),
                        monthi , diem
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void docFilePT(String fileName) {
        try {
            dsPT = (ArrayList) db1.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }
       public void docFileTS(String fileName) {
        try {
            dsTS = (ArrayList) db1.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }

       public void docFileMT(String fileName) {
        try {
            dsMT = (ArrayList) db1.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }
        public void docFileKQ(String fileName) {
        try {
            dsKQ = (ArrayList) db1.readDataFromFile(fileName);
            System.out.println(" đọc được file");
        } catch (Exception ex) {
            System.out.println("không đọc được file");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Đại học Công Nghiệp Hà Nội");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(185, 185, 185)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã KQ", "Họ Tên", "SBD", "Môn", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tìm Theo SBD: ");

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tblVeModel.setRowCount(0);
        String SBD = jTextField1.getText();
        for(ThiSinh t:dsTS){
            if(SBD == null ? t.getsBD() == null : SBD.equals(t.getsBD())){
                String mamonthi = null, maketqua = "---",
                        diem = "chua co",monthi = null , tensv = null;                
                for(PhongThi pt : dsPT){
                    if(pt.getMaPhong().equals(t.getMaPhong())){
                        mamonthi = pt.getMaMonThi();
                    }
                }
                for(MonThi mt : dsMT){
                    if(mt.getMaMonThi().equals( mamonthi)){
                         monthi = mt.getTenMonThi();
                    }
                }
                for(SinhVien sv : dsTVCC){
                    if(sv.getMaSV().equals(t.getMaSV())){
                         tensv = sv.getTenSV();
                    }
                }

                for(KetQua kq : dsKQ){
                    if(kq.getsBD().equals(t.getsBD())){
                        maketqua = kq.getMaKetQua();
                        diem = Float.toString(kq.getDiem());
                    }
                }
                tblVeModel.addRow(new Object[]{ maketqua, tensv, t.getsBD(),
                        monthi , diem
                });
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetQuaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetQuaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetQuaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetQuaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KetQuaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private String ToString(float diem) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
