/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlphongthi.giaodienAdmin;

import CLassController.GiamThi;
import CLassController.GiaoVien;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ThemGiamThi extends javax.swing.JDialog {

    /**
     * Creates new form ThemGiamThi
     */
    private GiamThiManager dsgt;
    static String fileNameGT = "giamthi.txt";
    ArrayList<GiamThi> dsGT = new ArrayList<>();
    public ThemGiamThi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fakeTV();
        this.setLocationRelativeTo(null);
        dsgt = (GiamThiManager) parent;
        dsgt.docFileGT(fileNameGT);
        dsGT = dsgt.dsGT;
    }

    
     ArrayList<GiaoVien> dsTVCC = new ArrayList<>();

    public void fakeTV() {
        GiaoVien a = new GiaoVien("GV1", "Nguyễn Văn A", 1990, "CNTT");
        GiaoVien b = new GiaoVien("GV2", "Nguyễn Văn B", 1990, "CNTT");
        GiaoVien c = new GiaoVien("GV3", "Nguyễn Văn C", 1990, "CNTT");
        GiaoVien d = new GiaoVien("GV4", "Nguyễn Văn D", 1990, "CNTT");
        GiaoVien e = new GiaoVien("GV5", "Nguyễn Văn E", 1990, "CNTT");
       
        dsTVCC.add(a);
        dsTVCC.add(b);
        dsTVCC.add(c);
        dsTVCC.add(d);
       dsTVCC.add(e);


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã Giám Thị");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Thêm Giám Thị");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1)
                        .addGap(66, 66, 66)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         boolean isMSV = false;
        boolean isMTV = true;
        for (GiaoVien a : dsTVCC) {
            if (a.getMaGiaoVien().equals(jTextField1.getText())) {
                isMSV = true;
            }
        }
        for (GiamThi a : dsGT) {
            if (a.getMaGiamThi().equals(jTextField1.getText())) {
                isMTV = false;
            }
        }
        if (jTextField1.getText() == "" ) {
            JOptionPane.showMessageDialog(rootPane, "khong duoc de trong o nao");
        } else {
            if (isMSV == false) {
                JOptionPane.showMessageDialog(rootPane, "khong co giam thi nao trung khop");
            } else if (isMTV == false) {
                JOptionPane.showMessageDialog(rootPane, "giao vien nay da la thanh vien");
            } else {
                
                    GiamThi b = new GiamThi();
                    for (GiaoVien a : dsTVCC) {
//            System.out.println(a.getmSV() );
//            System.out.println(jTextField1.getText());

                        if (a.getMaGiaoVien().equals(jTextField1.getText())) {
                            //b = a;
                            // b=new SinhVien(a.getTen(),a.getmSV(),a.getDiaChi(),a.getKhoa(),a.getLopUT(),a.getGiaoVien());
                            b.setTenGiamThi(a.getTenGiaoVien());
                            b.setMaGiamThi(a.getMaGiaoVien());
                           
                        }
                    }
                    System.out.println(b);
                    dsgt.AddThanhVien(b);
                    JOptionPane.showMessageDialog(rootPane, "them thanh cong!!");
                

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemGiamThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemGiamThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemGiamThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemGiamThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiamThiManager danhSachTV = new GiamThiManager();
                ThemGiamThi dialog = new ThemGiamThi(danhSachTV, true);

                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
